In [8]:
import pandas as pd
import numpy as np

In [9]:
traindataset=pd.read_csv(r"C:\Users\91954\Desktop\Medical recommandation system\datasets\Training.csv")

In [10]:
traindataset.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   
3           0         0             0                    0   
4           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   
3                     0                   0        0                     0   
4                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  
3                  0  Fungal infection  
4                  0  Fungal infection  

[5 rows x 133 columns]

In [11]:
traindataset.shape

(4920, 133)

In [12]:
traindataset.dtypes

itching                  int64
skin_rash                int64
nodal_skin_eruptions     int64
continuous_sneezing      int64
shivering                int64
                         ...  
inflammatory_nails       int64
blister                  int64
red_sore_around_nose     int64
yellow_crust_ooze        int64
prognosis               object
Length: 133, dtype: object

In [13]:
traindataset.columns.unique()

Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'continuous_sneezing',
       'shivering', 'chills', 'joint_pain', 'stomach_pain', 'acidity',
       'ulcers_on_tongue',
       ...
       'blackheads', 'scurring', 'skin_peeling', 'silver_like_dusting',
       'small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'yellow_crust_ooze', 'prognosis'],
      dtype='object', length=133)

In [14]:
x=traindataset.iloc[:,:-1]
y=traindataset["prognosis"]

In [18]:
pip install scikit-learn


  Using cached scikit_learn-1.6.1-cp312-cp312-win_amd64.whl.metadata (15 kB)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.1 MB 12.2 MB/s eta 0:00:01
   ----------------- ---------------------- 5.0/11.1 MB 12.6 MB/s eta 0:00:01
   -------------------- ------------------- 5.8/11.1 MB 10.1 MB/s eta 0:00:01
   ----------------------- ---------------- 6.6/11.1 MB 7.7 MB/s eta 0:00:01
   ------------------------- -------------- 7.1/11.1 MB 6.8 MB/s eta 0:00:01
   ----------------------------- ---------- 8.1/11.1 MB 6.5 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/11.1 MB 6.1 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.1 MB 5.8 MB/s eta 0:00:01
   ---------------------------------------  11.0/11.1 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 5.5 MB/s eta 0:00:00
Using cached j


[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
from sklearn.preprocessing import LabelEncoder

In [20]:
encoder=LabelEncoder()
encoder=encoder.fit(y)
y=encoder.transform(y)

In [21]:
print(y)

[15 15 15 ... 38 35 27]


In [22]:
from sklearn.model_selection import train_test_split


In [23]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=0)


In [24]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [25]:
models = {
    "SVC":SVC(kernel="linear"),
    "RandomForestClassifier":RandomForestClassifier(n_estimators=100,random_state=42),
    "GradientBoostingClassifier":GradientBoostingClassifier(n_estimators=100,random_state=42),
    "KNeighborsClassifier":KNeighborsClassifier(n_neighbors=5),
    "DecisionTreeClassifier":DecisionTreeClassifier(random_state=42),
    "MultinomialNB":MultinomialNB()
}

for model_name,model in models.items():
  model.fit(X_train,Y_train)
  y_pred=model.predict(X_test)
  accuracy=accuracy_score(Y_test,y_pred)
  cm=confusion_matrix(Y_test,y_pred)
  cr=classification_report(Y_test,y_pred)
  print(f"Accuracy for {model_name} : {accuracy}")
  print(f"confusion matrix for{model_name}:{cm}")
  print(f"classification report for{model_name}:{cr}")




Accuracy for SVC : 1.0
confusion matrix forSVC:[[32  0  0 ...  0  0  0]
 [ 0 31  0 ...  0  0  0]
 [ 0  0 38 ...  0  0  0]
 ...
 [ 0  0  0 ... 36  0  0]
 [ 0  0  0 ...  0 38  0]
 [ 0  0  0 ...  0  0 38]]
classification report forSVC:              precision    recall  f1-score   support

           0       1.00      1.00      1.00        32
           1       1.00      1.00      1.00        31
           2       1.00      1.00      1.00        38
           3       1.00      1.00      1.00        34
           4       1.00      1.00      1.00        33
           5       1.00      1.00      1.00        36
           6       1.00      1.00      1.00        39
           7       1.00      1.00      1.00        41
           8       1.00      1.00      1.00        33
           9       1.00      1.00      1.00        35
          10       1.00      1.00      1.00        42
          11       1.00      1.00      1.00        27
          12       1.00      1.00      1.00        33
          1

In [26]:
model=SVC(kernel="linear")
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)
accuracy=accuracy_score(Y_test,y_pred)
print(accuracy)

1.0


In [27]:
import pickle

In [28]:
with open("models/svc.pkl","wb") as f:
  pickle.dump(model,f)

In [29]:
prd=model.predict(X_test.iloc[0].values.reshape(1,-1))


c:\Users\91954\Desktop\Medical recommandation system\venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [30]:
prd
Y_test[0]

np.int64(18)

In [31]:
Symtomsdataset=pd.read_csv(r"C:\Users\91954\Desktop\Medical recommandation system\datasets\symtoms_df.csv")
discriptiondataset=pd.read_csv(r"C:\Users\91954\Desktop\Medical recommandation system\datasets\description.csv")
medicationdataset=pd.read_csv(r"C:\Users\91954\Desktop\Medical recommandation system\datasets\medications.csv")
dietsdataset=pd.read_csv(r"C:\Users\91954\Desktop\Medical recommandation system\datasets\diets.csv")
precautiondataset=pd.read_csv(r"C:\Users\91954\Desktop\Medical recommandation system\datasets\precautions_df.csv")
Workoutdataset=pd.read_csv(r"C:\Users\91954\Desktop\Medical recommandation system\datasets\workout_df.csv")

In [32]:
dietsdataset.head()

Disease                                               Diet
0     Fungal infection  ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...
1              Allergy  ['Elimination Diet', 'Omega-3-rich foods', 'Vi...
2                 GERD  ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...
3  Chronic cholestasis  ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...
4        Drug Reaction  ['Antihistamine Diet', 'Omega-3-rich foods', '...

In [33]:
Symtomsdataset.shape

(4920, 6)

In [34]:
precautiondataset.head()

Unnamed: 0         Disease                      Precaution_1  \
0           0   Drug Reaction                   stop irritation   
1           1         Malaria          Consult nearest hospital   
2           2         Allergy                    apply calamine   
3           3  Hypothyroidism                     reduce stress   
4           4       Psoriasis  wash hands with warm soapy water   

                   Precaution_2        Precaution_3  \
0      consult nearest hospital    stop taking drug   
1               avoid oily food  avoid non veg food   
2       cover area with bandage                 NaN   
3                      exercise         eat healthy   
4  stop bleeding using pressure      consult doctor   

                  Precaution_4  
0                    follow up  
1           keep mosquitos out  
2  use ice to compress itching  
3             get proper sleep  
4                   salt baths

In [35]:
Workoutdataset.head()

Unnamed: 0.1  Unnamed: 0           disease                    workout
0             0           0  Fungal infection         Avoid sugary foods
1             1           1  Fungal infection         Consume probiotics
2             2           2  Fungal infection  Increase intake of garlic
3             3           3  Fungal infection     Include yogurt in diet
4             4           4  Fungal infection      Limit processed foods

In [36]:
def helper(disease):
  descr=discriptiondataset[discriptiondataset["Disease"]==disease]["Description"]
  desc=" ".join([w for w in descr])

  pre=precautiondataset[precautiondataset["Disease"]==disease][["Precaution_1","Precaution_2","Precaution_3","Precaution_4"]]
  pre=([col for col in pre.values])

  med=medicationdataset[medicationdataset["Disease"]==disease]["Medication"]
  med=([med for med in med.values])

  Diet=dietsdataset[dietsdataset["Disease"]==disease]["Diet"]
  Diet=([diet for diet in Diet.values])

  workout=Workoutdataset[Workoutdataset["disease"]==disease]["workout"]


  return desc,pre,med,Diet,workout



In [37]:
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}


In [ ]:

def get_predicted(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    valid = False
    for symptom in patient_symptoms:
        if symptom in symptoms_dict:
            input_vector[symptoms_dict[symptom]] = 1
            valid = True
        else:
            print(f"Warning: Symptom '{symptom}' not recognized.")

    if not valid:
        print("No valid symptoms entered. Cannot predict.")
        return None

    prediction = model.predict([input_vector])[0]
    return diseases_list[prediction]

# 🔽 Get user input
sympthons = input("Enter your symptoms (comma-separated): ")
user_symptoms = [s.strip().lower() for s in sympthons.split(",")]

# 🔍 Predict
predicted_disease = get_predicted(user_symptoms)
if predicted_disease:
    print("Predicted Disease:", predicted_disease)


In [ ]:
desc,pre,med,Diet,workout =helper(predicted_disease)

In [ ]:


# --- Prediction Function ---
def get_predicted(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    valid = False
    for symptom in patient_symptoms:
        if symptom in symptoms_dict:
            input_vector[symptoms_dict[symptom]] = 1
            valid = True
        else:
            print(f"⚠️ Warning: Symptom '{symptom}' not recognized.")

    if not valid:
        print("❌ No valid symptoms entered. Cannot predict.")
        return None

    prediction = model.predict([input_vector])[0]
    return diseases_list[prediction]

# --- Helper Function ---
def helper(disease):
    descr = discriptiondataset[discriptiondataset["Disease"] == disease]["Description"]
    desc = " ".join([w for w in descr])

    pre = precautiondataset[precautiondataset["Disease"] == disease][["Precaution_1", "Precaution_2", "Precaution_3", "Precaution_4"]]
    pre = [item for sublist in pre.values.tolist() for item in sublist]

    med = medicationdataset[medicationdataset["Disease"] == disease]["Medication"].tolist()
    diet = dietsdataset[dietsdataset["Disease"] == disease]["Diet"].tolist()
    workout = Workoutdataset[Workoutdataset["disease"] == disease]["workout"].tolist()

    return desc, pre, med, diet, workout

# --- User Input ---
symptoms_input = input("Enter your symptoms (comma-separated): ")
user_symptoms = [s.strip().lower() for s in symptoms_input.split(",")]

# --- Predict and Display ---
predicted_disease = get_predicted(user_symptoms)

if predicted_disease:
    print("\n✅ Predicted Disease:", predicted_disease)

    desc, pre, med, diet, workout = helper(predicted_disease)

    print("\n📝 Description:")
    print(desc)

    print("\n💊 Precautions:")
    for p in pre:
        print(f"- {p}")

    print("\n🧪 Medications:")
    for m in med:
        print(f"- {m}")

    print("\n🥗 Recommended Diet:")
    for d in diet:
        print(f"{d}")

    print("\n🏃 Workout Suggestions:")
    for w in workout:
        print(f"- {w}")


Enter your symptoms (comma-separated): cough, chest_pain, phlegm

✅ Predicted Disease: Heart attack

📝 Description:
Heart attack is a sudden and severe reduction in blood flow to the heart muscle.

💊 Precautions:
- call ambulance
- chew or swallow asprin
- keep calm
- nan

🧪 Medications:
- ['Compression stockings', 'Exercise', 'Elevating the legs', 'Sclerotherapy', 'Laser treatments']

🥗 Recommended Diet:
['Heart-Healthy Diet', 'Low-sodium foods', 'Fruits and vegetables', 'Whole grains', 'Lean proteins']

🏃 Workout Suggestions:
- Follow a heart-healthy diet
- Limit sodium intake
- Include fiber-rich foods
- Consume healthy fats
- Include lean proteins
- Limit sugary foods and beverages
- Stay hydrated
- Consult a healthcare professional
- Follow medical recommendations
- Engage in regular exercise


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(
